### PR TITLE
Crude fix for other text input windows taking control while trying to type into the search bar

### PR DESCRIPTION
**Pull request by CampbellReid**
I've been noticing that I can only input a character at a time in the search window, so I have attempted to write a fix for it. It is not perfect and it quite hacky but now it only perhaps 1/20 characters enter other text inputs vs every character like before.

### CODE REVIEW

**Comment by polywock** [comment]
Hello. I haven't noticed this issue. Can you describe it a bit more, or a way to reproduce the issue?

**Comment by CampbellReid** [comment]
Apologies. It was quite late when I wrote the description.
It happens on Firefox. I managed to replicate it in two different firefox browsers, one on Windows and one on Linux.
I should've waited to submit the PR but considering checking on chrome it is okay, perhaps it is a different issue than using the fix I described.

**Comment by CampbellReid** [comment]
I decided to take another look at how ChatGPT's input box functioned. For whatever reason I didn't notice the content editable before which allows users to input into it. By only enabling it when the search box is blurred, this solution seems to work a lot better. Now it just watches for blur changing and disables or enables the input box depending on that.

**Comment by polywock** [comment]
Thanks! Didn't know this was an issue until now. 

Merged but also simplified further in f79cefc252. Seems like they're listening to keypress event and focusing on the ChatCPT prompt input when triggered. Simplified the approach further by stopping the event if the extension's search box is active. 

```js 
window.addEventListener("keypress", e => {
    const shadow = (e.target as any)?.shadowRoot as ShadowRoot
    if (shadow && shadow.activeElement?.tagName === "INPUT") e.stopImmediatePropagation()
}, true)
```

**Pull request merged**
